yoga/Models/MembershipCard.cs
using System.ComponentModel.DataAnnotations;

namespace yoga.Models
{
    public class MembershipCard
    {
        public MembershipCard()
        {
            AppUser = new AppUser();
        }
        [Key]
        public int CardId { get; set; }
        public string? SerialNumber { get; set; }
        public DateTime? ExpireDate { get; set; }
        public bool? Payed { get; set; } = false;
        public bool? Active { get; set; } = false;

        [Display(Name = "Bank Receit Copy")]
        public string RecietCopy { get; set; }
        public decimal? Price { get; set; }
        public int Status { get; set; } = (int)StatusEnum.Pending;
        public virtual AppUser AppUser { get; set; }
    }
}

yoga/Controllers/MembershipCardController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using yoga.Data;
using yoga.Helpers;
using yoga.Models;
using yoga.ViewModels;

namespace yoga.Controllers
{
    public class MembershipCardController: Controller
    {
        private readonly YogaAppDbContext _db;
        private readonly UserManager<AppUser> _userManager;

        private readonly NotificationHelper _notificationHelper;

        private readonly IWFHistoryManager _wfHistoryManager;
        // private readonly IEmailSender _emailSender;
        public MembershipCardController(YogaAppDbContext db, 
        UserManager<AppUser> userManager, IWFHistoryManager wfHistoryManager
        )
        {
            _db = db;
            _userManager = userManager;
            _notificationHelper = new NotificationHelper(_db);
            _wfHistoryManager = wfHistoryManager;
        }

        public IActionResult Index()
        {
            IEnumerable<MembershipCard> cards = _db.MembershipCards.Include("AppUser");
            return View(cards);
        }
        
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(MembershipCardVM obj, IFormFile RecietCopy, IFormFile Image, int id)
        {
            ModelState.Remove("RecietCopy");
            ModelState.Remove("Image");
            if(ModelState.IsValid)
            {
                // Upload image
                string fileName = "";
                if(RecietCopy == null || RecietCopy.Length == 0)
                {
                    ModelState.AddModelError("RecietCopy", "Receipt Copy Is required");
                    return View(obj);
                }
                if(RecietCopy != null && RecietCopy.Length > 0)
                {
                    fileName = Path.GetFileName(RecietCopy.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/assets/images", fileName);
                    using (var fileSrteam = new FileStream(filePath, FileMode.Create))
                    {
                        await RecietCopy.CopyToAsync(fileSrteam);
                    }
                }

                string userId = _userManager.GetUserId(User);
                var loggedUser = _db.Users.Where(u=>u.Id == userId).FirstOrDefault();
                if(loggedUser == null)
                {
                    ModelState.AddModelError("", "User Not Exist");
                    return View();
                }

                // validate user image
                if(string.IsNullOrEmpty(loggedUser.UserImage))
                {
                    // Upload image
                    string fileName_image = "";
                    if(Image != null && Image.Length > 0)
                    {
                        fileName_image = Path.GetFileName(Image.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/assets/images", fileName_image);
                        using (var fileSrteam = new FileStream(filePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(fileSrteam);
                        }
                        // update user image column
                        var user = _db.Users.Find(loggedUser.Id);
                        if(user != null)
                        {
                            user.UserImage = fileName_image;
                            _db.Users.Update(user);
                            _db.SaveChanges();
                        }
                    }
                    else 
                    {
                        ModelState.AddModelError("Image", "Image is rquired");
                        return View(obj);    
                    }
                }


                if(id > 0)
                {
                    var entity_forUpdate = _db.MembershipCards.Find(id);
                    entity_forUpdate.RecietCopy = fileName;
                    entity_forUpdate.Status = (int)StatusEnum.Pending;
                    _db.MembershipCards.Update(entity_forUpdate);
                }
                else
                {
                    MembershipCard entity_forCreate = new MembershipCard
                    {
                        AppUser = loggedUser,
                        RecietCopy = fileName
                    };

                    _db.MembershipCards.Add(entity_forCreate);
                }
                

                await _db.SaveChangesAsync();

                // Add user to member role
                await _userManager.AddToRoleAsync(loggedUser, "Member");
                
                string confirmationMessage = "Your request has been sent successfully. Our team will review it and approve it as soon as possible. Thank you.";
                ViewData["Saved"] = confirmationMessage;
                EmailConfiguration _emailConfiguration = new EmailConfiguration();
                EmailSender _emailSender = new EmailSender(_emailConfiguration);
                    
                string content = $"Dear {loggedUser.UserName}, We hope this message finds you in good health. We are delighted to inform you that we have successfully received your request for a membership card. Our dedicated team is currently reviewing and processing your application, ensuring that it receives the attention and efficiency it deserves.Upon approval of your membership card request, you will gain access to an array of exclusive benefits, services, and opportunities available to esteemed members of our community.If any additional information is required to complete the process, one of our representatives will promptly reach out to you for further details.We sincerely appreciate your interest in joining as a member, and we eagerly look forward to welcoming you to our organization. If you have any questions or concerns, please do not hesitate to contact our customer support team at info@yoga.sa.Thank you for selecting us as your preferred organization. We strive to make your membership experience truly fulfilling.Warm regards, Membership Services Team";
                
                var emailMessage = new EmailMessage
                {
                    ToEmailAddresses = new List<string> {loggedUser.Email},
                    Subject = "SAUDI YOGA COMMITTEE - MemberShip Card Rquest",
                    Body = content
                };

                // Generate pdf license

                // Add notification
                
                _notificationHelper.AddNotify(new Notification
                {
                    AppUser = loggedUser,
                    Body = content,
                    Title = "Create Membership Card",
                    CreationDate = DateTime.Now,
                    IsRead = false
                });

                // add wfhistory
                WFHistory wfHistory = new WFHistory();
                wfHistory.AppUser = loggedUser;
                wfHistory.WFHistoryType = WFHistoryTypeEnum.CreateMembership;
                wfHistory.RecordId = id;
                wfHistory.CreationDate = DateTime.Now;
                wfHistory.ModuleName = "Membership";
                wfHistory.Description = "Create membership card";
                int wfSaved = _wfHistoryManager.Save(wfHistory);
            
                _emailSender.SendEmailBySendGrid(emailMessage);

                ViewData["Saved"] = confirmationMessage;
                return RedirectToAction("DataSaved");
            }
            return View();
        }
        public IActionResult DataSaved()
        {
            return View();
        }

        public IActionResult Detail(int? id)
        {
            if(id == null || id == 0) return NotFound();
            var obj = _db.MembershipCards.Include("AppUser").Where(m=>m.CardId == id).SingleOrDefault();
            if(obj == null) return NotFound();

            return View(obj);
        }

        // //Post
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public IActionResult Detail(MembershipCard obj)
        // {
        //     if(ModelState.IsValid)
        //     {
        //         _db.MembershipCards.Update(obj);
        //         _db.SaveChanges();
        //         return View(obj);
        //     }
        //     return View();
        // }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Detail(int id, string Approve, string reason)
        {
            if(!string.IsNullOrEmpty(Approve))
            {
                var memCard = _db.MembershipCards.Include("AppUser").Where(m=>m.CardId == id).SingleOrDefault();
                // Update status, payed, active and expire date for 1 year
                memCard.Active = true;
                memCard.Payed = true;
                memCard.ExpireDate = DateTime.Now.AddYears(1);
                memCard.Status = (int)StatusEnum.Approved;
                
                // Generate card serial
                var serials = _db.MembershipCards.Select(m=>m.SerialNumber).ToList();
                string serialNumber = YogaUtilities.GenerateSerialNumber(serials);
                memCard.SerialNumber = $"{memCard.CardId}{serialNumber}";
                _db.MembershipCards.Update(memCard);
                int rowAffect = _db.SaveChanges();
                // Send Email to the user(Congratuilation, Your Membership card is active now until {expire date}, Your)
                // Card Serial Number "999"
                string userImage = memCard?.AppUser?.UserImage;

                string content = @$"<div>
                        <p>

yoga/Views/MembershipCard/Create.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@model yoga.ViewModels.MembershipCardVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@inject UserManager<AppUser> userManager
@{
    var user = await userManager.GetUserAsync(User);
    var imagePath = user.UserImage;
}


<link href="~/assets/css/account-details.css" rel="stylesheet">


<div class="d-lg-flex">
    <partial name="_AdminMenu" />
   

    <div class="account-container account-details">

        <form method="post" enctype="multipart/form-data">
            @if (ViewData["Saved"] != null)
            {
                <div class="alert alert-success">@ViewData["Saved"]</div>
            }

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <h2>@localizer["PageTitle"]</h2>

            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="border p-3 mt-4">
                <div class="alert alert-info">@localizer["plzSend"] <span class="fw-bold">150</span> @localizer["sar"]
                </div>
                @* <div class="alert alert-danger"><span class="fw-bold">@localizer["BillNoteTitle"]</span> @localizer["BillNote"]
                </div> *@

                <div class="mb-3">
                    <label class="fw-bold">@localizer["Price"]</label>
                    <label>150 ريال سعودي</label>
                </div>

                <div class="mb-3">
                    <label class="fw-bold">@localizer["IBAN"]</label>
                    <label>SA5865000000101459418001</label>
                </div>

                <div class="mb-3">
                    <label class="fw-bold" asp-for="RecietCopy">@localizer["BankReceitCopy"]</label>
                    <input type="file" asp-for="RecietCopy" class="form-control" />
                    <span asp-validation-for="RecietCopy" class="text-danger"></span>
                </div>

                @if (string.IsNullOrEmpty(imagePath))
                        {
                            <div class="mb-3">
                                <div id="upload-container" class="text-center">
                                    <label>
                                        <img src="~/assets/images/public/upload.png" />
                                        <br />

                                        <input asp-for="Image" id="inputTag" class="upload-text" type="file" />
                                        <span asp-validation-for="Image" class="text-danger"></span>
                                        <br />
                                        <p class="extensions" id="imageName">
                                            JPG , PNG , PFD
                                        </p>
                                    </label>
                                </div>
                            </div>
                        }

                <button type="submit" class="btn btn-brown-outline about-btn">@localizer["Apply"]</button>
        </form>
    </div>
    <partial name="_bankInfo" />
</div>

</div>

</div>

</div>

</div>













@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

yoga/Views/MembershipCard/DataSaved.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/assets/css/account-details.css" rel="stylesheet">

<div class="d-lg-flex">
    <partial name="_AdminMenu" />
    <div class="account-container account-details">


    
        <div class="alert alert-success">@localizer["ConfirmMessage"]</div>
        <div><a asp-controller="Account" asp-action="UserProfile">@localizer["backBtn"]</a></div>


</div>
</div>

yoga/Views/MembershipCard/Detail.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@model MembershipCard;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/assets/css/account-details.css" rel="stylesheet">


<div class="d-lg-flex">
                <partial name="_AdminMenu"/>
                <div class="account-container account-details">
                    
                    <form method="post" enctype="multipart/form-data">
            @if(ViewData["Saved"] != null)
            {
                <div class="alert alert-success">@ViewData["Saved"]</div>
            }
            <h2>@localizer["MembershipCardDetails"]</h2>
            <div class="border p-3 mt-4">
                <div class="mb-3">
                    <label class="fw-bold">@localizer["Name"]</label>
                    <label>@Model?.AppUser.FirstName</label> <label>@Model?.AppUser.MiddleName</label> <label>@Model?.AppUser.LastName</label>
                </div>

                <div class="mb-3">
                    <label class="fw-bold">@localizer["MembershipCardPrice"]</label>
                    <label>150 ريال سعودي</label>
                </div>

                <div class="mb-3">
                    <label class="fw-bold">IBAN</label>
                    <label>SA5865000000101459418001</label>
                </div>
                <div class="mb-3">
                    <label class="fw-bold" asp-for="RecietCopy">@localizer["RecietCopy"]</label>
                    <img width="400" height="400" src="~/assets/images/@Model?.RecietCopy" alt="">
                </div>

                <div class="mb-3">
                    <label class="fw-bold" asp-for="Active">@localizer["Active"]</label>
                    <label>
                        @if(@Model?.Active== true){
                            <span class="badge bg-success">@localizer["Yes"]</span>
                        }
                        else {
                            <span class="badge bg-danger">@localizer["No"]</span>
                        }
                    </label>
                </div>

                
                @if(@Model.Status != (int)StatusEnum.Approved)
                {
                        <div class="mb-3">
                            <button type="submit" class="btn btn-success" id="Approve" name="Approve" value="approve">@localizer["Approve"]</button>
                        </div>
                        <div class="mb-3">
                            <label>@localizer["RejectReason"]</label>

                        </div>
                        <div class="mb-3">
                            <textarea name="reason" id="reason" cols="30" rows="3"></textarea>

                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-danger" value="reject" id="Reject" name="Reject">@localizer["Reject"]</button>
                        </div>
                }
                </form>
            </div>
            </div>
    
                </div>
</div>

yoga/Views/MembershipCard/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@model IEnumerable<MembershipCard>
@{
    ViewData["Title"] ="Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/assets/css/account-details.css" rel="stylesheet">

        <div class="d-lg-flex">
                <partial name="_AdminMenu"/>
                <div class="account-container account-details">
                    <h2 class="header page-header">@localizer["PageTitle"]</h2>
                    <a asp-controller="MembershipCard" asp-action="ExportToExcel">@localizer["Export"]</a>

                    <div class="tab-content" id="orders-table-tab-content">
			        <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
					    <div class="app-card app-card-orders-table shadow-sm mb-5">
						    <div class="app-card-body">
							    <div class="table-responsive">
							        <table class="table app-table-hover mb-0 text-left">
										<thead>
											<tr>
                                                <th>@localizer["Name"]</th>
                                                <th>@localizer["Phone"]</th>
                                                <th>@localizer["Email"]</th>
                                                <th>@localizer["CardSerial"]</th>
                                                <th>@localizer["PayFees"]</th>
                                                <th>@localizer["Status"]</th>
                                                <th>@localizer["Actions"]</th>
											</tr>
										</thead>
										<tbody>
                                    @foreach (var item in Model)
                                    {
                                                <tr>
                                                    <td class="cell">
                                                @item.AppUser.FirstName @item.AppUser.MiddleName @item.AppUser.LastName
                                                    </td>
                                                    <td class="cell">
                                                @item.AppUser.PhoneNumber
                                                    </td>
                                                    <td class="cell">
                                                @item.AppUser.Email
                                                    </td>
                                                    <td class="cell">
                                                @item.SerialNumber
                                                    </td>
                                            @if (@item.Payed == false)
                                            {
                                                        <td class="cell">No</td>
                                            }
                                            else
                                            {
                                                        <td class="cell">Yes</td>
                                            }
                                            @if (@item.Status == 2)
                                            {
                                                        <td class="cell"> <span class="badge bg-success">Approved</span> </td>
                                            }
                                            else if(item.Status == 1)
                                            {
                                                        <td class="cell"> <span class="badge bg-info">Pending</span> </td>
                                            }
                                            else if(item.Status == 3)
                                            {
                                                        <td class="cell"> <span class="badge bg-danger">Rejected</span> </td>
                                            }

                                            
                                                    <td>
                                                        <div class="w-75 btn-group" role="group">
                                                            <a class="btn-sm app-btn-secondary" asp-controller="MembershipCard" asp-action="Detail"
                                                            asp-route-id="@item.CardId"><i class="fa-solid fa-memo-circle-info"></i>@localizer["Details"]</a>
                                                        </div>
                                                    </td>

                                                </tr>
                                    }
		
										</tbody>
									</table>
						        </div><!--//table-responsive-->
						    </div><!--//app-card-body-->		
						</div><!--//app-card-->
			        
                    </div>
                </div><!--//tab-content-->
                </div>
            </div>