yoga/Controllers/TeacherLicController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using yoga.Data;
using yoga.Models;
using yoga.ViewModels;
using System.Linq;
using yoga.Helpers;
using System.Globalization;

namespace yoga.Controllers
{
    public class TeacherLicController : Controller
    {
        private readonly YogaAppDbContext _db;
        private readonly ILogger<TeacherLicController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly NotificationHelper _notificationHelper;
        private readonly IWFHistoryManager _wfHistoryManager;

        public TeacherLicController(ILogger<TeacherLicController> logger,
        YogaAppDbContext db, UserManager<AppUser> userManager, 
        IWFHistoryManager wfHistoryManager)
        {
            _logger = logger;
            _db = db;
            _userManager = userManager;
            _notificationHelper = new NotificationHelper(_db);
            _wfHistoryManager = wfHistoryManager;
        }

        public IActionResult CreateDemo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateDemo(CreateDemoVM obj)
        {
            return View(obj);
        }

        public IActionResult PreIndex()
        {
            IEnumerable<TechearMemberShip> lics = _db.TechearMemberShips
            .Include("TechearMemberShipTests")
            .Include(t=>t.AppUser);
            return View(lics);
        }
        public IActionResult Index(int Id)
        {
            IEnumerable<TechearMemberShipTest> lics = _db.techearMemberShipTests
            .Include("TechearMemberShip")
            .Include(t=>t.TechearMemberShip.AppUser)
            .Where(m=>m.TechearMemberShip.MemId == Id)
            .ToList();

            foreach (var item in lics)
            {
                item.TeachingType_string = GlobalHelpers.getTeachingType(item.TeachingType);
                //item.MemId = 
            }
            return View(lics);
        }

        private List<SelectListItem> getEducationLevels()
        {
            var culture = Request.HttpContext.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();

            List<SelectListItem> levels = new List<SelectListItem>();
            levels.Add(new SelectListItem
            {
                Text = culture.RequestCulture.UICulture.Name == "en" ? "Select Level" : "اختر المستوي",
                Value = string.Empty
            });

            levels.Add(new SelectListItem
            {
                Text = "Level 1 - 100 hrs",
                Value = "1"
            });

            levels.Add(new SelectListItem
            {
                Text = "Level 2 - 200 hrs",
                Value = "2"
            });

            levels.Add(new SelectListItem
            {
                Text = "Level 3 - 300 hrs",
                Value = "3"
            });
            return levels;
        }

        public List<SelectListItem> getTeachingTypes()
        {
            List<SelectListItem> t_Types = new List<SelectListItem>();
            // t_Types.Add(new SelectListItem
            // {
            //     Text = "Select Teaching Type",
            //     Value = string.Empty
            // });

            t_Types.Add(new SelectListItem
            {
                Text = "Yin",
                Value = "1"
            });

            t_Types.Add(new SelectListItem
            {
                Text = "Prenatal",
                Value = "2"
            });

            t_Types.Add(new SelectListItem
            {
                Text = "Therapy",
                Value = "3"
            });
            t_Types.Add(new SelectListItem
            {
                Text = "Aerial",
                Value = "4"
            });
            t_Types.Add(new SelectListItem
            {
                Text = "Hatha",
                Value = "5"
            });
            t_Types.Add(new SelectListItem
            {
                Text = "Ashtanga",
                Value = "6"
            });
            t_Types.Add(new SelectListItem
            {
                Text = "Vinyasa Flow",
                Value = "7"
            });
            t_Types.Add(new SelectListItem
            {
                Text = "Iyengar",
                Value = "8"
            });
            return t_Types;
        }

        [Authorize]
        public IActionResult Create()
        {
            var member = IfTeacherExists(0);
            if (member != null) return View(member);
            var vm = new TechearMemberShipVM();
            vm.EducationLevels = getEducationLevels();
            vm.TeachingTypes = getTeachingTypes();
            ViewBag.TeachingTypes = getTeachingTypes();
            
            // if (ViewData["SavedFiles"] != null)
            // {
            //     vm.CertficateFiles = ViewData["SavedFiles"].ToString();
            // }
            vm.TechearMemberShipTestVMs.Add(new TechearMemberShipTestVM{TestId=1,ExamDetails = "", AccreditedHours = 0});
            return View(vm);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(TechearMemberShipVM obj, IFormFile CertficateFiles,
        IFormFile Image, string[] TeachingTypesList)
        {
            ModelState.Remove("TeachingTypes");
            ModelState.Remove("ReceiptCopy");
            ModelState.Remove("CertficateFiles");
            ModelState.Remove("Agreement");
            ModelState.Remove("ExamDetails");
            ModelState.Remove("SchoolSocialMediaAccount");
            ModelState.Remove("Name");
            ModelState.Remove("PersonalWebSite");
            ModelState.Remove("EducationLevels");
            ModelState.Remove("Image");
            ModelState.Remove("TeachingType");
            obj.Name = "tst";
            ModelState.Remove("TeachingTypesList");
            foreach (var item in obj.TechearMemberShipTestVMs)
            {
                ModelState.Remove("ExamDetails");
                ModelState.Remove("TeachingTypes");
                ModelState.Remove("TeachingTypesList");
            }

            // if (TeachingTypesList.Count() == 0)
            // {
            //     obj.EducationLevels = getEducationLevels();
            //     obj.TeachingTypes = getTeachingTypes();
            //     ModelState.AddModelError("TeachingType", " Teaching Type is required");
            // }
            if (obj.EducationLevel == 0)
            {
                obj.EducationLevels = getEducationLevels();
                obj.TeachingTypes = getTeachingTypes();
                ModelState.AddModelError("EducationLevel", " Education Level is required");
            }

            if (ModelState.IsValid)
            {
                if (!obj.Agreement)
                {
                    obj.EducationLevels = getEducationLevels();
                    obj.TeachingTypes = getTeachingTypes();
                    ModelState.AddModelError("Agreement", " Terms Conditions and Acknowledged");
                    return View(obj);
                }

                


                // get logened user
                string userId = _userManager.GetUserId(User);
                var loggedUser = _db.Users.Where(u => u.Id == userId).FirstOrDefault();
                if (loggedUser == null)
                {
                    ModelState.AddModelError("", "User Not Exist");
                    return View(obj);
                }

                // validate user image
                if (string.IsNullOrEmpty(loggedUser.UserImage))
                {
                    // Upload image
                    string fileName = "";
                    if (Image != null && Image.Length > 0)
                    {
                        fileName = Path.GetFileName(Image.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/assets/images", fileName);
                        using (var fileSrteam = new FileStream(filePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(fileSrteam);
                        }
                        // update user image column
                        var user = _db.Users.Find(loggedUser.Id);
                        if (user != null)
                        {
                            user.UserImage = fileName;
                            _db.Users.Update(user);
                            _db.SaveChanges();
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Image", "Image is rquired");
                        obj.EducationLevels = getEducationLevels();
                        obj.TeachingTypes = getTeachingTypes();
                        return View(obj);
                    }
                }

                TechearMemberShip entity = new TechearMemberShip();
                entity.AppUser = loggedUser;
                entity.Id = userId;
                entity.EducationLevel = (EducationLevelEnum)obj.EducationLevel;
                entity.SocialMediaAccounts = obj.SocialMediaAccounts;
                entity.PersonalWebSite = obj.PersonalWebSite;
                if(entity.TeachingType != null) entity.TeachingType = obj.TeachingType.Value;
                entity.ExpYears = obj.ExpYears.Value;
                
                //entity.CertficateFiles = uploadFiles == null ? "" : string.Join(",", uploadFiles);
                entity.Name = obj.Name;

                // validate innter cert items
                if(obj.TechearMemberShipTestVMs.Count != Request.Form.Files.Count)
                {

yoga/Views/TeacherLic/Confirmation.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/assets/css/account-details.css" rel="stylesheet">

<div class="d-lg-flex">
    <partial name="_AdminMenu" />
    <div class="account-container account-details">


    
        <div class="alert alert-success">Your request has been sent successfully. Our team will review it and approve it as soon as possible. Thank you.</div>
        <div><a asp-controller="Account" asp-action="UserProfile">Go to Your profile to see the licence status</a></div>


</div>
</div>

yoga/Views/TeacherLic/CreateDemo.cshtml
@model yoga.ViewModels.CreateDemoVM

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" enctype="multipart/form-data">
<div asp-validation-summary="All" class="text-danger"></div>
    <select asp-for="LevelId">
        <option value="">Select Level</option>
        <option value="1">Level 1</option>
        <option value="2">Level 2</option>
        <option value="3">Level 3</option>
    </select>

    <span asp-validation-for="LevelId" class="text-danger"></span>

    <div>
        <button>Submit</button>
    </div>
</form>


@section Scripts {
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<partial name="_ValidationScriptsPartial" />


}

yoga/Views/TeacherLic/CreateSingleLic.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@model yoga.ViewModels.TechearMemberShipTestVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject UserManager<AppUser> userManager
@{
    var user = await userManager.GetUserAsync(User);
    var imagePath = user.UserImage;
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="~/chosen_v1.8.7/chosen.css">

<div class="yoga-layout">
    <div class="public-pages">
        <form method="post" enctype="multipart/form-data">

            @if (ViewData["Saved"] != null)
            {
                <div class="alert alert-success">@ViewData["Saved"]</div>
                <div><a asp-controller="Account" asp-action="UserProfile">Go to Your profile to see the licence status</a>
                </div>
            }



                <h2>Teacher Licence Item</h2>
                <div asp-validation-summary="All" class="text-danger"></div>
                <span class="text-danger" id="spAgreement"></span>


                    <div class="formgroup">
                        <label>Teaching type</label>
                        <select id="TeachingTypesList" class="form-control" data-placeholder="Select Teaching types"
                            asp-for="@Model.TeachingType" asp-items="@Model.TeachingTypes">
                        </select>
                        @* <span asp-validation-for="@Model.TechearMemberShipTestVMs[i].TeachingType"
                        class="text-danger"></span> *@

                    </div>
                    <div class="formgroup">
                        <label asp-for="AccreditedHours">Accredited Hours</label>
                        <input asp-for="AccreditedHours" id="AccreditedHours" class="form-control" />
                        
                        @* @Html.EditorFor(x => x.AccreditedHours,
                                 new { htmlAttributes = new { @class = "form-control" } }) *@
                        <span asp-validation-for="@Model.AccreditedHours" class="text-danger"></span>
                    </div>
                    <div class="formgroup">
                        <label asp-for="SchoolLocation"> School Location </label>
                        <input asp-for="SchoolLocation" id="SchoolLocation" class="form-control" />
                       
                        @* @Html.EditorFor(x => x.SchoolLocation,
                                 new { htmlAttributes = new { @class = "form-control" } }) *@
                        <span asp-validation-for="@Model.SchoolLocation" class="text-danger"></span>
                    </div>
                    <div class="formgroup">
                        <label asp-for="CertaficateDate">Certaficate Date </label>
                        <div class="saveCanInput EventDateInput">
                            <input type="date" asp-for="CertaficateDate" asp-format="yyyy-mm-dd"
                                class="form-control Datepicker" />
                        </div>



                        <span asp-validation-for="@Model.CertaficateDate" class="text-danger"></span>
                        @* <span class="fw-bold">@localizer["certNote"]</span> *@
                    </div>
                    <div class="formgroup">
                        <label asp-for="SchoolName">School Name</label>
                        <input asp-for="SchoolName" id="SchoolName" class="form-control" />
                        @* @Html.EditorFor(x => x.SchoolName,
                                 new { htmlAttributes = new { @class = "form-control" } }) *@
                        <span asp-validation-for="@Model.SchoolName" class="text-danger"></span>
                    </div>
                    <div class="formgroup">
                        <label asp-for="SchoolLink">School Link</label>
                        <input asp-for="SchoolLink" id="SchoolLink" class="form-control" />
                        @* @Html.EditorFor(x => x.SchoolLink,
                                 new { htmlAttributes = new { @class = "form-control" } }) *@
                        <span asp-validation-for="@Model.SchoolLink" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="SchoolSocialMediaAccount">School Social Media Account</label>
                        <input asp-for="SchoolSocialMediaAccount" id="SchoolSocialMediaAccount"
                        class="form-control" />
                        @* @Html.EditorFor(x => x.SchoolSocialMediaAccount,
                                 new { htmlAttributes = new { @class = "form-control" } }) *@
                        <span asp-validation-for="@Model.SchoolSocialMediaAccount" class="text-danger"></span>
                    </div>
                    <div class="formgroup">
                        <label asp-for="CertficateFiles">Certficate Files</label>
                        <input id="CertficateFiles" type="file" asp-for="CertficateFiles" class="form-control" />
                        @* @Html.EditorFor(x=> x.TechearMemberShipTestVMs[i].CertficateFiles,
                        new {htmlAttributes = new {@class = "form-control"}}) *@

                        @* <span asp-validation-for="@Model.TechearMemberShipTestVMs[i].CertficateFiles"
                        class="text-danger"></span> *@
                    </div>
                    <div class="formgroup">
                        <label></label>
                        <div></div>
                        <button type="submit" id="btnSubmit" class="btn btn-brown-outline about-btn">Submit</button>
                    </div>
                
                    <input type="hidden" id="hdnLastIndex" value="0">




                

        </form>
    </div>
</div>







@section Scripts {
    <script src="~/assets/js/jquery-3.6.0.js"></script>
    <script src="~/assets/js/jquery-ui.js"></script>
    <script src="~/chosen_v1.8.7/chosen.jquery.js" type="text/javascript"></script>
    <script src="~/chosen_v1.8.7/docsupport/init.js" type="text/javascript" charset="utf-8"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_ValidationScriptsPartial" />

    

}

yoga/Views/TeacherLic/DataSaved.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/assets/css/account-details.css" rel="stylesheet">

<div class="d-lg-flex">
    <partial name="_AdminMenu" />
    <div class="account-container account-details">


    
        <div class="alert alert-success">@localizer["ConfirmMessage"]</div>
        <div><a asp-controller="Account" asp-action="UserProfile">@localizer["backBtn"]</a></div>


</div>
</div>

yoga/Views/TeacherLic/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@model IEnumerable<TechearMemberShipTest>
@{
    ViewData["Title"] ="Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/assets/css/account-details.css" rel="stylesheet">

<div class="d-lg-flex">
                <partial name="_AdminMenu" />
                <div class="account-container account-details">
                    @* <h2 class="header page-header">@localizer["PageTitle"]</h2> *@
                    <h2 class="header page-header">@localizer["TeacherLicences"]</h2>
                    <a asp-controller="TeacherLic" asp-route-id='@ViewContext.RouteData.Values["Id"]' asp-action="ExportToExcel">@localizer["Export"]</a>

					<div class="table-responsive">
							        <table class="table app-table-hover mb-0 text-left">
										<thead>
											<tr>
                                                <th>@localizer["TestId"]</th>
                                                <th>@localizer["UserName"]</th>
                                                <th>@localizer["ExpYears"]</th>
                                                <th>@localizer["AccreditedHours"]</th>
                                                <th>@localizer["TeachingType"]</th>
                                                <th>@localizer["PayTestFees"]</th>
                                                <th>@localizer["PayLicenceFees"]</th>
                                                <th>@localizer["Status"]</th>
                                                <th>@localizer["PassExam"]</th>
                                                <th>@localizer["FinalApprove"]</th>
                                                <th>@localizer["Actions"]</th>
											</tr>
										</thead>
										<tbody>
											@* <tr>
												<td class="cell">#15346</td>
												<td class="cell"><span class="truncate">Lorem ipsum dolor sit amet eget volutpat erat</span></td>
												<td class="cell">John Sanders</td>
												<td class="cell"><span>17 Oct</span><span class="note">2:16 PM</span></td>
												<td class="cell"><span class="badge bg-success">Paid</span></td>
												<td class="cell">$259.35</td>
												<td class="cell"><a class="btn-sm app-btn-secondary" href="#">View</a></td>
											</tr> *@
                                    @foreach (var item in Model)
                                    {
                                                <tr>
                                                    <td class="cell">
                                                @item.TestId
                                                    </td>
                                                    <td class="cell">
                                                @item.TechearMemberShip.AppUser.FirstName  @item.TechearMemberShip.AppUser.MiddleName @item.TechearMemberShip.AppUser.LastName
                                                    </td>
                                                    <td class="cell">
                                                @item.TechearMemberShip.ExpYears
                                                    </td>
                                                    <td class="cell">
                                                @item.AccreditedHours
                                                    </td>
                                                    <td class="cell">
                                                @item.TeachingType_string
                                                    </td>
                                            @if (@item.PayExamFees == false)
                                            {
                                                        <td class="cell">Not Paid</td>
                                            }
                                            else
                                            {
                                                        <td class="cell">Paid</td>
                                            }
                                            @if (@item.PayFees == false)
                                            {
                                                        <td class="cell">Not Paid</td>
                                            }
                                            else
                                            {
                                                        <td class="cell">Paid</td>
                                            }
                                            @if (@item.Status == 2)
                                            {
                                                        <td class="cell"> <span class="badge bg-success">Approved</span> </td>
                                            }
                                            else if(@item.Status == 1)
                                            {
                                                        <td class="cell"> <span class="badge bg-info">Pending</span> </td>
                                            }
                                            else if(@item.Status == 3)
                                            {
                                                <td class="cell"> <span class="badge bg-danger">Rejected</span> </td>
                                            }

                                            @if (@item.PassExam == true)
                                            {
                                                        <td class="cell"> <span class="badge bg-success">Yes</span> </td>
                                            }
                                            else if(@item.PassExam == false)
                                            {
                                                        <td class="cell"> <span class="badge bg-danger">No</span> </td>
                                            }
                                            

                                            @if (@item.FinalApprove == true)
                                            {
                                                        <td class="cell"> <span class="badge bg-success">Approved</span> </td>
                                            }
                                            else
                                            {
                                                        <td class="cell"> <span class="badge bg-info">Pending</span> </td>
                                            }

                                            @* @if(@item.Status == 0)
                                                {
                                                <td>
                                                <button class="btn btn-info">Approve</button>
                                                |
                                                <button class="btn btn-danger">Reject</button>
                                                </td>
                                                }
                                                else {
                                                <td>
                                                <button class="btn btn-info">Approve</button>
                                                </td>
                                                } *@
                                                    <td>
                                                        <div class="w-75 btn-group" role="group">
                                                            <a class="btn-sm app-btn-secondary" asp-controller="TeacherLic" asp-action="Detail"
                                                            asp-route-id="@item.TestId"><i class="fa-solid fa-memo-circle-info"></i>@localizer["Details"]</a>
                                                        </div>
                                                    </td>

                                                </tr>
                                    }
		
										</tbody>
									</table>
						        </div><!--//table-responsive-->
                </div>
</div>

yoga/Views/TeacherLic/PayExamFees.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@model yoga.ViewModels.TechearMemberShipVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="border p-3 mt-4">
    <form method="post" enctype="multipart/form-data">

        @if (ViewData["Saved"] != null)
        {
            <div class="alert alert-success">@ViewData["Saved"]</div>
            <div><a asp-controller="Account" asp-action="UserProfile">Go to Your profile to see the licence status</a></div>
        }

        <h2>Pay Exam Fees</h2>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="alert alert-info">
            Please Send Exam Fees (500 SAR) to the below bank account
            <p>IBAN: SA5865000000101459418001</p>
            @* <p>Exam Details</p> *@
            @* <p>
                @if(@Model != null)
                {
                    @Model.ExamDetails
                }
            </p> *@
        </div>
        @* <div class="alert alert-danger"><span class="fw-bold">@localizer["BillNoteTitle"]</span> @localizer["BillNote"]
        </div> *@
        <div class="mb-3">
            <input type="hidden" value='@(ViewContext.RouteData.Values["Id"])' name="TestId">
            <label>Receipt </label>
            <input type="file" name="Receit" class="form-control" />
        </div>
        <div class="mb-3">
            <button class="btn btn-success" >Submit</button>
        </div>

    </form>
    <partial name="_bankInfo" />
</div>


@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

yoga/Views/TeacherLic/PreIndex.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@model IEnumerable<TechearMemberShip>
@{
    ViewData["Title"] ="Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/assets/css/account-details.css" rel="stylesheet">

<div class="d-lg-flex">
                <partial name="_AdminMenu" />
                <div class="account-container account-details">
                    @* <h2 class="header page-header">@localizer["PageTitle"]</h2> *@
                    <h2 class="header page-header">@localizer["Title"]</h2>
                    <a asp-controller="TeacherLic" asp-action="ExportToExcel">@localizer["Export"]</a>

					<div class="table-responsive">
							        <table class="table app-table-hover mb-0 text-left">
										<thead>
											<tr>
                                                <th>@localizer["Id"]</th>
                                                <th>@localizer["UserName"]</th>
                                                <th>@localizer["CreationDate"]</th>
                                                <th>@localizer["Actions"]</th>
											</tr>
										</thead>
										<tbody>
											@* <tr>
												<td class="cell">#15346</td>
												<td class="cell"><span class="truncate">Lorem ipsum dolor sit amet eget volutpat erat</span></td>
												<td class="cell">John Sanders</td>
												<td class="cell"><span>17 Oct</span><span class="note">2:16 PM</span></td>
												<td class="cell"><span class="badge bg-success">Paid</span></td>
												<td class="cell">$259.35</td>
												<td class="cell"><a class="btn-sm app-btn-secondary" href="#">View</a></td>
											</tr> *@
                                    @foreach (var item in Model)
                                    {
                                                <tr>
                                                    <td class="cell">
                                                @item.MemId
                                                    </td>
                                                    <td class="cell">
                                                @item.AppUser.FirstName  @item.AppUser.MiddleName @item.AppUser.LastName
                                                    </td>
                                                    <td class="cell">
                                                @item.CertaficateDate
                                                    </td>
                                                    <td>
                                                        <div class="w-75 btn-group" role="group">
                                                            <a class="btn-sm app-btn-secondary" asp-controller="TeacherLic" asp-action="Index"
                                                            asp-route-id="@item.MemId"><i class="fa-solid fa-memo-circle-info"></i>@localizer["View"]</a>
                                                        </div>
                                                    </td>

                                                </tr>
                                    }
		
										</tbody>
									</table>
						        </div><!--//table-responsive-->
                </div>
</div>